version: '3.3'

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.0
    ports:
      - "5044:5044"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf  
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  filebeat:
    user: root  
    image: docker.elastic.co/beats/filebeat:7.3.0
    volumes:
       - /var/lib/docker/containers:/var/lib/docker/containers:ro
    configs:
       - source: filebeat_config
         target: /usr/share/filebeat/filebeat.yml
    networks:
      - elk
    deploy:
      mode: global

configs:
  elastic_config:
    file: ./elk/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./elk/logstash/config/logstash.yml
  logstash_pipeline:
    file: ./elk/logstash/pipeline/logstash.conf
  kibana_config:
    file: ./elk/kibana/config/kibana.yml
  filebeat_config:
    file: ./filebeat/config/filebeat.stack.yml

networks:
  elk:
    driver: overlay
