version: '3.3'

services:

  elasticsearch:
    image: 127.0.0.1:5000/elasticsearch:7.3.0
    build: ./elk_stack/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: 127.0.0.1:5000/logstash:7.3.0
    build: ./elk_stack/logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: 127.0.0.1:5000/kibana:7.3.0
    build: ./elk_stack/kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    image: 127.0.0.1:5000/
    build: ./filebeat
    networks:
      - elk:
    deploy:
      mode: global

networks:
  elk:
    driver: overlay
